<a href="https://colab.research.google.com/github/mrunallll/Flipr-Hackathon--Stock-Prediction/blob/master/Task02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
#import pandas_profiling
from pandas import DataFrame
import seaborn as sns
import warnings
plt.style.use('ggplot')
plt.rcParams['figure.figsize']=(12,8)

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [2]:
from google.colab import files
up=files.upload()

Saving Put-Call_TS.xlsx to Put-Call_TS.xlsx

#DATA PREPROCESSING
1. transforming the data (rows into cols)
2. Dropping Stock Index feature
3. Handling missing values

In [4]:
put_call_data=pd.read_excel('Put-Call_TS.xlsx')
put_call_data = put_call_data.transpose()
put_call_data.head(10)

                     0         1        2     ...      3329      3330      3331
Stock Index           NaT    AC3235   AC3236  ...    AD2736    AD2737    AD2738
Put-Call Ratio 2020-08-10       0.8     0.86  ...      0.67      0.79      0.74
Unnamed: 2     2020-08-11      0.66    0.732  ...     0.504     0.648     0.588
Unnamed: 3     2020-08-12    0.7724  0.85448  ...   0.59456   0.75872   0.69032
Unnamed: 4     2020-08-13  0.983224  1.08664  ...  0.759146  0.965987  0.879803
Unnamed: 5     2020-08-14  0.901211  1.01704  ...  0.650243  0.881906   0.78538
Unnamed: 6     2020-08-15  0.898368  1.02926  ...  0.614775  0.876553  0.767479

[7 rows x 3332 columns]

In [15]:
#put_call_data.drop(['Stock Index'], inplace=True)
put_call_data.head(10)

   2020-08-10 2020-08-11 2020-08-12 2020-08-13 2020-08-14 2020-08-15
1         0.8       0.66     0.7724   0.983224   0.901211   0.898368
2        0.86      0.732    0.85448    1.08664    1.01704    1.02926
3        0.93      0.816    0.95024     1.2073        NaN    1.18196
4        1.09      1.008    1.16912    1.48309    1.46106      1.531
5         NaN      1.104    1.27856    1.62099     1.6155    1.70552
6         NaN      1.152    1.33328    1.68993    1.69272    1.79278
7        1.23      1.176    1.36064    1.72441    1.73134    1.83641
8           1        0.9      1.046    1.32796    1.28732    1.33467
9           1        0.9      1.046    1.32796    1.28732    1.33467
10       1.07      0.984        NaN    1.44862        NaN    1.48737

In [60]:
put_call_data = put_call_data.transpose()

In [12]:
put_call_data.rename(columns={'Put-Call Ratio': '2020-08-10', 'Unnamed: 2': '2020-08-11', 'Unnamed: 3': '2020-08-12', 'Unnamed: 4': '2020-08-13','Unnamed: 5': '2020-08-14', 'Unnamed: 6': '2020-08-15'}, inplace=True)

In [14]:
put_call_data.drop([0], axis=0, inplace=True)

In [21]:
put_call_data.shape

(3331, 6)

In [19]:
put_call_data = put_call_data.transpose()

In [22]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values= np.nan, strategy='mean')
imp = imp.fit(put_call_data.iloc[:, 0:6])
put_call_data.iloc[:, 0:6] = imp.transform(put_call_data.iloc[:, 0:6])

In [23]:
put_call_data.isnull().sum()

2020-08-10    0
2020-08-11    0
2020-08-12    0
2020-08-13    0
2020-08-14    0
2020-08-15    0
dtype: int64

In [61]:
put_call_data.head(10)

                1         2         3     ...      3329      3330      3331
2020-08-10  0.800000  0.860000  0.930000  ...  0.670000  0.790000  0.740000
2020-08-11  0.660000  0.732000  0.816000  ...  0.504000  0.648000  0.588000
2020-08-12  0.772400  0.854480  0.950240  ...  0.594560  0.758720  0.690320
2020-08-13  0.983224  1.086645  1.207302  ...  0.759146  0.965987  0.879803
2020-08-14  0.901211  1.017042  1.165254  ...  0.650243  0.881906  0.785380
2020-08-15  0.898368  1.029258  1.181962  ...  0.614775  0.876553  0.767479

[6 rows x 3331 columns]

In [25]:
put_call_data.describe()

        2020-08-10   2020-08-11  ...   2020-08-14   2020-08-15
count  3331.000000  3331.000000  ...  3331.000000  3331.000000
mean      0.938828     0.825080  ...     1.165254     1.201216
std       0.187999     0.242628  ...     0.384289     0.425595
min       0.600000     0.420000  ...     0.515107     0.462070
25%       0.790000     0.612000  ...     0.843295     0.832924
50%       0.938828     0.816000  ...     1.165254     1.201216
75%       1.080000     1.032000  ...     1.480367     1.552815
max       1.290000     1.248000  ...     1.847166     1.967298

[8 rows x 6 columns]

In [51]:
put_call_data = put_call_data.transpose()

#Using  LSTM  model

In [ ]:
# multivariate output stacked lstm example
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

In [63]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in range(len(sequences)):
		end_ix = i + n_steps
		if end_ix > len(sequences)-1:
			break
		seq_x, seq_y = sequences[i:end_ix, :], sequences[end_ix, :]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)
 
# defining input sequence
in_seq0 = put_call_data.iloc[0, :].values
in_seq1 = put_call_data.iloc[1, :].values
in_seq2 = put_call_data.iloc[2, :].values
in_seq3 = put_call_data.iloc[3, :].values
in_seq4 = put_call_data.iloc[4, :].values
in_seq5 = put_call_data.iloc[5, :].values

out_seq = array([in_seq0[i]+in_seq1[i]+in_seq2[i]+in_seq3[i]+in_seq4[i]+in_seq5[i] for i in range(len(in_seq0))])

In [ ]:
# converting to [rows, columns] structure
in_seq0 = in_seq0.reshape((len(in_seq0), 1))
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
in_seq3 = in_seq3.reshape((len(in_seq3), 1))
in_seq4 = in_seq4.reshape((len(in_seq4), 1))
in_seq5 = in_seq5.reshape((len(in_seq5), 1))

out_seq = out_seq.reshape((len(out_seq), 1))

In [ ]:
#making a datset with rows, columns
dataset = hstack((in_seq0, in_seq1, in_seq2, in_seq3, in_seq4, in_seq5, out_seq))
n_steps = 3
X, y = split_sequences(dataset, n_steps)
n_features = X.shape[2]

In [ ]:
#model
model = Sequential()
model.add(LSTM(100, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
model.add(LSTM(100, activation='relu'))
model.add(Dense(n_features))
model.compile(optimizer='adam', loss='mse')
# fitting model
model.fit(X, y, epochs=400, verbose=0)

In [66]:
df_output=pd.DataFrame(dataset)

After finding output sequence (16th Aug Put-Call Ratio), exported the array in form of dataframr to csv in drive to access the further 16th Aug Put-Call Ratio. 

Now using the same exported file lstm (2) and train_dataset to predict stock pricesprices

In [88]:
new=pd.read_excel('lstm (2).xlsx')

In [89]:
new.shape

(3331, 7)

In [90]:
new.head()

          0      1        2         3         4         5         6
0  0.800000  0.660  0.77240  0.983224  0.901211  0.898368  5.015203
1  0.860000  0.732  0.85448  1.086645  1.017042  1.029258  5.579425
2  0.930000  0.816  0.95024  1.207302  1.165254  1.181962  6.250759
3  1.090000  1.008  1.16912  1.483091  1.461062  1.531000  7.742274
4  0.938828  1.104  1.27856  1.620986  1.615504  1.705519  8.263397

In [94]:
train_data=pd.read_excel('Train_dataset.xlsx')
train_data.head()

  Stock Index    Index  ... P/B Ratio  Stock Price
0         AA1     NYSE  ...      9.20   156.987852
1         AA2     NYSE  ...      6.91   560.859622
2         AA3     NYSE  ...      6.09  1279.732874
3         AA4      BSE  ...      5.60  1121.787632
4         AA5  S&P 500  ...      9.46   382.962534

[5 rows x 15 columns]

In [95]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values= np.nan, strategy='mean')
imp = imp.fit(train_data.iloc[:, 12:13])
train_data.iloc[:, 12:13] = imp.transform(train_data.iloc[:, 12:13])

In [99]:
X_train= train_data.iloc[:, 12:13].values
y_train= train_data.iloc[:, -1].values
X_test= new.iloc[:, 6:7].values

In [112]:
from sklearn.preprocessing import PolynomialFeatures
polyreg= PolynomialFeatures(degree=4)
X_poly= polyreg.fit_transform(X_train)
lin_reg = LinearRegression()
lin_reg.fit(X_poly, y_train)
X_test_poly= polyreg.fit_transform(X_test)

y_pred_poly= lin_reg.predict(X_test_poly)
r2 = cross_val_score(lin_reg, X_poly, y_train, cv=10, scoring='r2')

In [100]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV

lasso=Lasso()
parameters={'alpha':[1e-15,1e-10,1e-8,1e-3,1e-2,1,5,10,20,30,35,40,45,50,55,100]}
scores = {
    'r2': 'r2',
    'nmse': 'neg_mean_squared_error'
}
lasso_regressor=GridSearchCV(lasso, parameters, refit='r2', scoring=scores, cv=10)
lasso_regressor.fit(X_train,y_train)
y_pred_lasso= lasso_regressor.predict(X_test)

print(lasso_regressor.best_params_)
print(lasso_regressor.best_score_)
print(lasso_regressor.cv_results_['mean_test_r2'])
print(lasso_regressor.cv_results_['mean_test_nmse'])

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4480014.151836395, tolerance: 118772.52950230274
  positive)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 147583856.75936794, tolerance: 119884.68750176473
  positive)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 31337107.343002558, tolerance: 120162.22560018118
  positive)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 196463851.16203225, tolerance: 119851.99664029399
  positive)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 287846303.9394934, tolerance: 118926.69102578245
  positive)

{'alpha': 1}
-0.0020337273132351452
[-0.00217863 -0.00217863 -0.00217863 -0.00217816 -0.00217402 -0.00203373
 -0.00203373 -0.00203373 -0.00203373 -0.00203373 -0.00203373 -0.00203373
 -0.00203373 -0.00203373 -0.00203373 -0.00203373]
[-179766.53214441 -179766.53214441 -179766.53214357 -179766.44737727
 -179765.6866901  -179740.07174934 -179740.07174934 -179740.07174934
 -179740.07174934 -179740.07174934 -179740.07174934 -179740.07174934
 -179740.07174934 -179740.07174934 -179740.07174934 -179740.07174934]

In [114]:
df_poly=pd.DataFrame(y_pred_poly)